# This file was generated by GoReleaser. DO NOT EDIT.
class Warriorrec < Formula
  desc "A CLI tool for getting Warrior Recreation schedules."
  homepage "https://github.com/stevenxie/warriorrec"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/stevenxie/warriorrec/releases/download/v0.1.0/warriorrec-0.1.0-macOS-x86_64.zip"
    sha256 "ae3cccccd8263e471d8adf9b9181f8943467b29726f92555f69c962ac5ef75b5"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/stevenxie/warriorrec/releases/download/v0.1.0/warriorrec-0.1.0-linux-x86_64.tar.gz"
      sha256 "8947599c6377282b29ce70dd158305088288628fd83ee87fc2482176c00f5a5a"
    end
  end

  def install
    bin.install "warriorrec"
  end

  test do
    warriorrec --version
  end
end
