# This file was generated by GoReleaser. DO NOT EDIT.
class Warriorrec < Formula
  desc "A CLI tool for getting Warrior Recreation schedules."
  homepage "https://github.com/stevenxie/warriorrec"
  version "0.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/stevenxie/warriorrec/releases/download/v0.1.1/warriorrec-0.1.1-macOS-x86_64.zip"
    sha256 "3096be5f993100b671eb75dcd60019dfddd69e85de46f618ea2540094827afed"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/stevenxie/warriorrec/releases/download/v0.1.1/warriorrec-0.1.1-linux-x86_64.tar.gz"
      sha256 "f7019c0255a240f32165327cb33b26c851201376f3fc14b9f9566430caa256e5"
    end
  end

  def install
    bin.install "warriorrec"
  end

  test do
    warriorrec --version
  end
end
